---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-secret
    template:
      engineVersion: v2
      data:
        READARR__API_KEY: "{{ .api_key }}"
        READARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: &dbUser "{{ .postgres_username }}"
        READARR__POSTGRES__PASSWORD: &dbPass "{{ .postgres_password }}"
        READARR__POSTGRES__MAIN_DB: readarr_main
        READARR__POSTGRES__LOG_DB: readarr_log
        INIT_POSTGRES_DBNAME: readarr_main readarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: readarr
    - extract:
        key: cloudnative-pg
