---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: PIA VPN
        property: openvpn_username
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: PIA VPN
        property: openvpn_password
    - secretKey: SERVER_REGIONS
      remoteRef:
        key: PIA VPN
        property: openvpn_server_regions
