apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:knVdXA312Q+kNo5+K3iAHs09MiYRWf6KIjG3jG56MW9iTuki6j5rlIRuGscR0kFW9qXNdcFyNIF1/mzR1P/cuzNq6K+C2q6Qs5XgTRUev3nTdy0Htc881/XQ/iHKTixqCq32OU0PA4cVflie6ACd8HmU2sEkjaelZ+IvjBVcpF3JPyBAw4MoG+A/Z6ZBVy/HeB67PNlSPPoTd7Ub/lO93Tdfq8cSp/uT+je6a91oHsRobvZRzxaTUo17OBlLuldMDK53okgts6RhiVoo/K7RqriXGZhbyUujAYbAvwce7wHLhPsL2kNe29BGew3IIwVoam1g6p0HQ7EhW9c/5/QMiTlBsZHs8OSKRvbIXnb59l2mj50eOY1T48PsVrBMBFNMgg==,iv:zSKg3yK1p8kzpgJXXvTCg+2AqlqW5taLrhKfSZLZsvk=,tag:+2VaTogZI56xGGWz4NDDtw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaVlvM3VEQnd4ZnB0SW9J
            cEsreW10Tm1ZSU8xM0Y5V3k2Yzl0dnY3dVZNCmtJcDNlbTVtWVI5a1hUTUxRUURF
            WTdMUXZwK1RvZFlQc05DTWFObmc2R3cKLS0tIFk1YTFXcG5qUVNJU25PTlVJSVBE
            RTRxdHdhU2I1bDJQa3BBdGVtc0hvWFUKEB1UoxYOMzAXcaAshdV6ygeN8w2akwxr
            5XIQomU6ugutGSu2CVyJEypcoxTzvv/t9tKYnQsnOpgmtv4BXeTr4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:27:37Z"
    mac: ENC[AES256_GCM,data:37aS9Om7oVyIh2elNsAxv9Ul6mI2IRgizE1Zvd6gIC6iLQvPG+DDUnh81BZfthjHg4rE6nOKjoZatyntsKSwSsbljI2hCYBpKrg017kXXmIaCV5TvsreSFiJhHpb1vw6JBnQWQb78px2AjV+jZC0jEHWxLBxKhLnRvjOavb74qQ=,iv:25UYFPiD0zklzHLO5XGdGvap7oFFYkHZAfVySruSGAE=,tag:BMHyTvNATSlqVlCc+1f0vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
