apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:HhejVzDs7+SKbA3tOiVA6PGz+Si20yNXfGWHIaC2s84cOVmqobYYCh9nb771KdERmU8AWbUWRLBWqcq1iAyVT7fIwQXFxlkaKh1T/wo4pQv1iFJFkaaKFS3PCcU9A/nEMmAj/cyW+FExNRLexXxtVvfQTbJWzUNpWqmVia+jl+99Vci+hg2AxR6rV9U9wbxij1GT/esvrw+eojr90tx7QHOasy2MyylWeLBHatQ3gUDEm4ewokRUPhRgQy6IgrTZS3XB9298EAiGA44FZ1/DNMpPYM3b9VUBbA/8MChNps+xhTSRGV/D5DKSQuCG8ld2tAVp8mPx8aYuvjsjTK5eeTrHZjryOC81D1FRAY8WG7E7EXP81ULLTIZUQpPNMuAq5w==,iv:YHVuhPr9/oAL1lYojfnRS3QIcF7WEB8h+CGKquDDgA0=,tag:iKaNQSNHt3juyyVhgsrDxQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNUsxd1lOcUVaZC9KUXR6
            TGpLTDI2TnR1cFlFYTVSK0RLK1RWNnBFdGprCnpnb0txWTNSK01zK1RRbmhXaGhB
            OTg2Z3JiSm84anFoelFQRUdwMFRRZWcKLS0tIEF4bDdUVUR4OW9zZi9jWk51Q09s
            MWFEK3dIc2ROQzhKbDc0UmVRWnlobHMKps2jMaBsi64JuxMAr0mwkYmMSQ3jhP37
            AkNzSYnvRgWpUs1YPrdi61fRmwMhNocItvOezNBQvW38YmU79ScoEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:14Z"
    mac: ENC[AES256_GCM,data:YRA7Y1Q0i4CQQdHtPcw5d5b8hgULhP26XD3kSBOtAUdpUqkDGBEqgsUb9Bs4E6EFGB7LJNE9lyRU3xaudk56pt0Vw/pgU0j4t2FvO9OJqaQIwPOAE7hQh/O2viu3OJrLn+Hrfz2V88Xmr7TLzx15w0vDQ0yKaGMen46TlNk9wM8=,iv:dMPHqpOy+eaAbsKKZKZs9i47iwgTy6D6kFyTxXIP4iM=,tag:nBVJ36Hm1OlhWjcApVB+JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
