apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:g8fQAoYIGDEJLept95qbvpa1cutftf9IHxc8pZeXnoDprnzkRpdMtNK/mBi9pfTR08goQpD58c68DxXOGnC28nY5ftfzErVjUq9lmpYXPVm2E/uK6uLMb4D3XGfrJSsIgM+gCzyi+86A2eFzwRy77XYUq3t773A/7ZLRr6fOE5w1UPM3NBvstdT9k77CT3HaRNqtVPiOGZ11tOVHjYTrmUoRPxfr43g8zRGmnzRukY6Pmo6E2+aGy0xre3o3tgYwcoKKlj4WX797ZfUuBetzoDkynQ17x9TBBaINcHdxSCfups+rbO6B53UQV+cOMpct9T5zspBzZBVCr9+uipQH0+IWST5gn/YlP3qCUtqb5F3Hcx247Cnbq+yl+IKB1LSMyg==,iv:gd8w9mpL2XQAvQdkQXO5cH8EgOH2m6qfql6txRQ3yHQ=,tag:9Ph8l78Uryhsr/VHQKZS8g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZU5pa0gzSkhEUGFsdjFo
            WHNhQlYxc0tpODJCeFBPNGdxcUphdkx0VzB3CkpNcmRIRHo3Z01hQjg3OE9WdC9w
            dzBpRDZTZkl6K1F1a29yaVlTZHlFdmcKLS0tIFlCeGhDR2hIbkM4dE9kNFlWSzdy
            V3hERTY4V0pZeCtVVDNMS0VEVGFXRFEKuwAi+caWUoOf14Jfmq/697KAE15BJ5AG
            mABbYkZKpkOK4l0T6pQsZYsoZO65FPsWDgVZaJ+uTFYa/TAEMXYodg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:18Z"
    mac: ENC[AES256_GCM,data:VRZKi1ep9B5NaMzaayQ+kqbhJxmmpDOkjd5cXnDlPpE/XXEjYc0ZjkjmhF8OQP3mDpVMdgbdAlRdI10bD1m+OvTjIHpcsydYCpBdam/EHHK9zUM5d4a+loEzA8VxdiprOIDVt+KoN7L0tcnV7IgeyEPOhjwD0E72OyeUcrEMv0s=,iv:3M46+imbqfrnzQ0G2v29IUNWdY/C1qbNWaBSh2YD/7c=,tag:85htViZIirJBf5J5oBxhow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
