---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app n8n
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: n8n-secret
        containers:
          app:
            image:
              repository: docker.io/n8nio/n8n
              tag: 1.63.2
            env:
              # Isolating N8N
              N8N_PERSONALIZATION_ENABLED: false
              N8N_VERSION_NOTIFICATIONS_ENABLED: false
              N8N_TEMPLATES_ENABLED: false
              # URL
              N8N_PORT: &port 5678
              N8N_HOST: &host "n8n.${SECRET_DOMAIN}"
              WEBHOOK_URL: "https://n8n.${SECRET_DOMAIN}"
              # Public API
              N8N_PUBLIC_API_DISABLED: true
              N8N_PUBLIC_API_SWAGGERUI_DISABLED: true

              NODE_FUNCTION_ALLOW_BUILTIN: "*"
              GENERIC_TIMEZONE: ${CONFIG_TIMEZONE}

              N8N_LOG_LEVEL: debug
              N8N_LOG_OUTPUT: console, file

              N8N_DIAGONISTICS_ENABLED: false
              N8N_HIRING_BANNER_ENABLED: false
              N8N_USER_MANAGEMENT_DISABLED: true

              N8N_METRICS: true
              N8N_USER_FOLDER: /n8n
              #NODE_FUNCTION_ALLOW_EXTERNAL: databricks/sql
            envFrom: *envFrom
    service:
      app:
        controller: n8n
        ports:
          http:
            port: *port

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: *app
          gethomepage.dev/icon: mdi:water-flow


        className: internal
        hosts:
          - host: n8n.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: n8n
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: n8n
        advancedMounts:
          n8n:
            n8n:
              - path: /n8n

    resources:
      requests:
        cpu: 20m
        memory: 128M
      limits:
        memory: 512M
