ansible_become_pass: ENC[AES256_GCM,data:ZJ2Mp902EJU=,iv:nMSFLbw88Ksm7MNhn/MZ0QNBy6y/B4eIIsrt0XXO4tE=,tag:ZW5BxjYgNjm1WvH2XVVIog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVk5najRUT1JOL2lsMzlB
            b3g3dmNFUGd2clFqTGs1ejIzS09DZ1B3clhJCjZyU0NOWkFHRUNDWVNOUm4rUndp
            dXJEdktTNTN2Z282K1d3SmRmOWkwdFUKLS0tIEdndGdvdkpWVjg5UXFkMWtJdEFx
            RW1WNzRSWEh6cDduZURCbTVuSU94NjQK4sJ8+594sbTkC5arM1CGM6vWEJJahKMf
            EMJVy0DmRw5gEXfGjF/tKBAxEOtMJEz7EPxAdGVQrTcXq0ifZ1MG4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:52:35Z"
    mac: ENC[AES256_GCM,data:a43EUmIf8qihDN4epD4ufyX0vZrsintQ7BdoyGxNTxw976Gr9pK39uAL5AZTAnjnXyyxlxapoAngkQQtXKPdt5uVlq0rhvd/2tkTSrvUH3Tl0o5Xe+Obqp+qlbwH6oOLjoCOiLND92ROk8xEPl237/p8p/pQVlkQkfIR0k4UQE4=,iv:ES7UnaaIDHp/qWvta3HsEVJCKIJDVELx02mNufE5CV8=,tag:s79sauFFjntATRQwuwaLZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
