ansible_become_pass: ENC[AES256_GCM,data:rkuNlyZTnjQ=,iv:C7Eykmn+qSdeCHKqHXX1uQbb0yS+WWZ7174IsPYRAgI=,tag:GhAEU8bFx7PqFqnlgStdlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TTZQUnBUcU8wdUpMejNa
            UUEzRWZxbE41dVpJY0VxWXYzNWdjRjRCU2dFCnJUTDV5Z01jenM3dUZqb1VEbU5G
            OFBXQjJadHREWURrYVRWRUl5ZG9pdUUKLS0tIGZlM1RtNjR2MHRwci9oN1djZit6
            YWYvMU5mUlJIMVlQcWlZd0JJNUlNR1EKeegJucqXraY5j93+/j3HzjovUECwWZFa
            iw69EaBTHa+seBBAIXWdz89WpEI0vfP+K1W/7OC4yMOyB1hP7RxI/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:26:51Z"
    mac: ENC[AES256_GCM,data:2WKtffVj4ZIfj/zwClAQUr7l0Zlj2PHk+gR9+YK2Wi7ywe4f5SrTaqCclmIYCb853stfEnfLNnYfdIMi8Fx0Hk35YGqhtR/uW7cHJFR+IdDr0r/UqQxdkRMsU5uJsWugrVZodsJxSfGEw3Uuy9cGxOZjqvUv/LGZFYf4YDy+AJI=,iv:TsQg0mVtVwyDeCmadkU2SEXsRfIJ0cpmQUjafyO5sng=,tag:YcM3q3zaT71xaSiiqzrS2Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
