ansible_become_pass: ENC[AES256_GCM,data:UyolbMEtk/4=,iv:thh9jgSrCytKaLrxPfzzbu+EInkDdS0pGQnMAGAF9bg=,tag:Tcuuno1oHxRRvxV1C/EthA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZE01WDVqcVRONzNCZ0FW
            S2ZKdHRBSGRNL1ZoQklQRlY4V2FBaFlNaVFrClNlamRyUEdmU2hYR3FvYTBlbWlO
            eSthTWRMUXdFbmExQUFGWjU1TzhxbzgKLS0tIFJZT0xxdnk2RlZFSzJ2M1V0cDl6
            UDZPN21ocnpMZDFVZC9iQzhpbEdrczgKuN9UxGVigJRcwgBiz6bNzs/Q3DMTsfIh
            yggF/xAgRI9mrESzFo6DNoIXKgpRW5cXh4l0abzqCukSmIPPdO3qjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:26:51Z"
    mac: ENC[AES256_GCM,data:bkgEPraZ5ugGNQz77wJ3p1nRssJDCpiN46910o2Nf/2cdnRSPyNNwo2A7LKUgYVWPanU6sO3UDfiZRIKR33TGPWrXNGrmOAcMP+bgIqr4kw/lU5p6YJnr6w/ULMCvkvEAfmIAjg6JZ7oxSlzufJtooZBpsA52IZTZcaasIY1daU=,iv:MwpW1C/VaukPrwden6e980KBvxXMvWt/GB0yL7f93JY=,tag:l/05BmZu29YfwA40HOAnVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
