ansible_become_pass: ENC[AES256_GCM,data:SJlr7aPAyo4=,iv:etODUsB6GJjzhoiuq/yWpwRObehTMIwv4t6y0IkSDEs=,tag:zG1y7d4BujaVQQjkO4xdiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM0theTFKTDlFRjdaNnc2
            Zkc0MXlQV2dkVHNZdGt4WnJ0S1lzNUQvYWxZCkwzZ3Z0Rno4Q3FZMndZMFFTZjdE
            a1lLYzNhbXNqTkxqK3VGL0dzcGZRTEEKLS0tIFN5ZUlwT1YzMjVZM0wxcm8vZjVp
            VHB3amJiRDE0VWxPZkdYQ3RPdFFNbGMKrcQfaPIs+EegwsZp1M4ZhtlgPATARMu5
            RR7sT3z9sBLfzgk8fTcRGv2qrosVxPHlGYYUDXJbxLFteGLOTWzVpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:41:30Z"
    mac: ENC[AES256_GCM,data:EaLZ65p7CDGfsb65/TdWMUToEc+0oK0879AsOIkGGKHPjsDX89PvHWMPb0O7p093G9ddB44Y/t4XdvC1UVkNHjKWBsgT1zDQNU27WMdPrvvdLDrkGbMapM4hqZbuBA/gSJlTIceMU4wqzVOvX22nYRSy041LEnEv9S5nOjWbgak=,iv:vak5Lr7csIDiaE8HyoG6DVTuA5Qn6Lm+p1qLhHSuaVg=,tag:M77EOeMslGIAAxbbdvq46A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
