ansible_become_pass: ENC[AES256_GCM,data:yS7TodBule0=,iv:7kj2YQGPGYEHQIJ3XzQm+i3mD0S9VfCdGBu+hjjxsG8=,tag:4C7hQUAZGgnoX9/q1f8Jug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc05ETFUxdDdkWldzRFhH
            NC82MnNBaDV5RU96Rk5BMTdoTk52NWovc3hZCmZtWnovakhLT3RWS0wrVjgycVZ0
            R0hjbEFtbmFQa3FJOUhwRVhSWUR1bmMKLS0tIHVOTVBmcGRhTGFSSStQelRLZXpt
            RXBEUXl4Q2xFNWVYRGk5a1VSVGNCb0UKhNjE/A1P+3k+piLpDjMHarO+vDo6IF7K
            Lul0oKp/XzuSi8djNAFu9LRsw+k5q1hv1zwkAtAyXQN/6GlBEgxF+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:41:30Z"
    mac: ENC[AES256_GCM,data:HNdJG2GH3oof95aKhFQ8kAZG+7MI2Nz0mNPYamzZJkHVj8bfZ/JvQrNHZ2S3GCzOXPqMladnJj+wsO2a2F4EmTSEA8CCy37XV8+VeLlqtJc4VbT3YFaIK0d9JGsOv7P/FZN7vbYLmfDaF2L9b8bsAzSZPrHr5nUavoSxFilwCv0=,iv:eZBtPtC1PMxxWlXCMLC6Duwz7DuRGyHDphAd/jScQVY=,tag:GUUMuwtefONDEAPPTadT/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
