---
apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
  name: rook-ceph-mon
  namespace: storage
stringData:
  cluster-name: storage
  admin-secret: ${ROOK_EXTERNAL_ADMIN_SECRET}
  ceph-secret: ${ROOK_EXTERNAL_USER_SECRET}
  ceph-username: ${ROOK_EXTERNAL_USERNAME}
  fsid: ${ROOK_EXTERNAL_FSID}
  mon-secret: ${ROOK_EXTERNAL_MONITOR_SECRET}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: storage
data:
  data: fog=${CEPH1_NODE}:3300,mist=${CEPH2_NODE}:3300
  mapping: '{"node":{}}'
  maxMonId: "2"
