---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lazylibrarian
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      readarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: linuxserver/lazylibrarian
              tag: version-2f9ad8bd
            env:
              PUID: 568
              GUID: 568
              TZ: ${CONFIG_TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
# Gag...TODO KILL THIS WITH FIRE ASAP
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 200m
                memory: 300Mi
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
# Gag...TODO KILL THIS WITH FIRE ASAP
        runAsNonRoot: false
    #     runAsUser: 568
    #     runAsGroup: 568
    #     fsGroup: 568
    #     fsGroupChangePolicy: OnRootMismatch
    #     supplementalGroups: [10000]
    #     seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: readarr
        ports:
          http:
            port: &port 5299
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hosts:
          - host: lazylibrarian.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: lazylibrarian
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /volume1/Media
        globalMounts:
          - path: /media
