---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi-driver
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: 0.9.5-pre.1
      sourceRef:
        kind: HelmRepository
        name: synology-csi-talos
        namespace: flux-system
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    clientInfoSecret:
      name: synology-csi-driver-credentials

    images:
      attacher:
        image: registry.k8s.io/sig-storage/csi-attacher
        pullPolicy: IfNotPresent
        tag: v4.6.1
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner
        pullPolicy: IfNotPresent
        tag: v5.0.1
      resizer:
        image: registry.k8s.io/sig-storage/csi-resizer
        pullPolicy: IfNotPresent
        tag: v1.11.2
      snapshotter:
        tag: v7.0.1
        image: registry.k8s.io/sig-storage/csi-snapshotter
        pullPolicy: IfNotPresent
      nodeDriverRegistrar:
        tag: v2.11.1
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar
        pullPolicy: IfNotPresent
      plugin:
        image: ghcr.io/zebernst/synology-csi
        pullPolicy: IfNotPresent
        # Defaults to {{ $.Chart.AppVersion }} if empty or not present:
        tag: v1.1.2

    storageClasses:
      syno-iscsi-delete:
        isDefault: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        parameters:
          protocol: iscsi
          dsm: ${SECRET_DSM_IP}
          location: '/volume1'
          formatOptions: "-E nodiscard"
          fstype: ext4
      syno-iscsi-retain:
        isDefault: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          protocol: iscsi
          dsm: ${SECRET_DSM_IP}
          location: '/volume1'
          formatOptions: "-E nodiscard"
          fstype: ext4

    volumeSnapshotClasses:
      syno-iscsi-delete:
        isDefault: false
        deletionPolicy: Delete
      syno-iscsi-retain:
        isDefault: false
        deletionPolicy: Retain
