apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:XmICIr+EiHQ+yuWB8ZDsLznaWDJfQ7+xBAjAogIEDc2t5Xl8/G9s8A==,iv:QdYF5JwcSw3+XNBlJcO/d6ne5VwUCx9JDigzWIkVc0U=,tag:VYWdLwEBf6S+T8iBoY7Qfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xgdtxuz0c6636aqzejt63kr0p8rutp6m0e6nmagnufc6mj5l0akqtqa2v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRVVsTnVyVW0xY3dvekVT
            YzZPSmkwUGFiZEx2V3B0dXJVc2RuNWRWamlzCnF5V2pHSVZ3L3FBVHEvVTI0WXd5
            dTY5dWJMM0EzRjExaVlmMXpJb01UTGMKLS0tIDRVZnA5NDh2c1NGZ00yN0NnZ0pm
            OFlJU3lCME5wYTNwZUFLUXZwb2dteU0KfRABmhXAa3G7kh6oIgrmiksvcF1Bvedc
            lnqdBFrk06sOlG5aZ/9JzzoW3Ryg4lXodx+6QlVnmanXcrpKKg/dZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-06T18:16:42Z"
    mac: ENC[AES256_GCM,data:ACC+exNn+hd5jSfRwldwYkgAZp/mpk4qi8FrNy9omIhB2kzaNtzIFL+5rabvb9mdkxzzBJbUDev9TTiIHr5yVluwbuTNpi598uGdd0JXBjuiO9SDGW9EJ+KXR0qjQ1VGS2WlKX38ebE0iU1FDNJG3kG3pYH6Vlit+ozJvXdcAOw=,iv:8iwUnRKMb6zP1eAVXJHbF/9vLgUADRAGwaK1guiBjGQ=,tag:K9s7AINBNjDZk8vCBDGS0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
