apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Tnp45ixPvYy0XI63m4TK0cQMO5pCOSQDZ4HZ1/0MoDxcWgAb,iv:/HwBhLWwLw59UbjpY61KtuXH0CZnVx/k0aq+Tr/L18k=,tag:qmKIwLV5fCVdjDz1sZhhug==,type:str]
    credentials.json: ENC[AES256_GCM,data:ZkeZTTb0tXLYw8uWWxwXiHM6+8WKhvt/IkJaL8EsswaZPnYOpZwlXjrG5pXiJjl+dA3JBUkTWSnZJyAmP47qBya7t7y/H1JP41HBl2SSpzIZkiafgcqL7JEMZkzkPylAcexAHXXRL1OHMN7Z6zOjpjVbp9dQglr7zm4yU3OGtIfYyZI=,iv:xxWcVWKemwiZ53GEkPzuntQcNmfXb3Uhm/e9/TNTuFc=,tag:SHF4UdTfeXKfnC3w4QH+Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xgdtxuz0c6636aqzejt63kr0p8rutp6m0e6nmagnufc6mj5l0akqtqa2v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMVNyMmNvTGNrazZaV3gv
            ZEJkMWNTdEh6cG93cnZ2bW0vbk14QURUNVFVCnAzTGdJOFc2dHJEVEdTa0NiS0Rr
            VjJBbkFZNHprM0wrdmpZTU51UEtBNU0KLS0tIFBGWG5qbHJPU0NNZFN3L0hnVVdK
            ZytEZEpBelppS051TTIzZWtiTCtGWlkKTtpkfbs+fZPQuv2LfC1wpWcwQM3bTBo0
            SKDf5lK7f8kQOFTxGPiQtkFFCWQmWyEz6rbUkK64i3oeVc8BS4HuZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-06T18:16:42Z"
    mac: ENC[AES256_GCM,data:td1IGYLuUzopLUPsPeQgl8YWq/XDdrDNkw0ZMDxsKk540tlQ2NF10d0Gk0OfCtZiaINkMj3EIUVMVl6RD/XSfdaLSwYRUp7pRh1PNobtHM+36f/pzMJ6AbKJd5pn+qPMz7JnPbTTkAqTFkYFIHuqYQeXEyx5ssUJCX4pCF/kH6k=,iv:mLNy1IX0HpNFNML4rwuws3X4BLFBdCK40DYQuEcJtiE=,tag:0F3ftCWhoXKKywwChCq1Ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
