---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      backend:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.5.4-rocm
            env:
              TZ: ${CONFIG_TIMEZONE}
              HSA_OVERRIDE_GFX_VERSION: 11.0.0
              HCC_AMDGPU_TARGETS: gfx1103
              OLLAMA_LLM_LIBRARY: rocm_v60102
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_MODELS: &pvc /models
            resources:
              requests:
                cpu: 200m
                memory: 8Gi
                amd.com/gpu: "1"
              limits:
                memory: 16Gi
                amd.com/gpu: "1"
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: amd.feature.node.kubernetes.io/gpu
                        operator: In
                        values:
                          - "true"
          nodeSelector:
            amd.feature.node.kubernetes.io/gpu: "true"
      ui:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.5.0
            env:
              WEBUI_NAME: Open WebUI Chat
              WEBUI_URL: https://chatgpt.${SECRET_DOMAIN}
              DATA_DIR: /data
              OLLAMA_BASE_URL: http://ollama-backend.default.svc.cluster.local:11434
              RAG_EMBEDDING_ENGINE: ollama
            envFrom:
              - secretRef:
                  name: openwebui-secret
            resources:
              requests:
                cpu: 200m
                memory: 2Gi
              limits:
                memory: 2Gi
    service:
      backend:
        controller: backend
        ports:
          http:
            port: &port 11434
      ui:
        controller: ui
        ports:
          http:
            port: &port 8080

    ingress:
      ui:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: "ChatGPT"
          gethomepage.dev/icon: sh-open-webui
          gethomepage.dev/description: "Open WebUI"
          gethomepage.dev/href: "https://chatgpt.${SECRET_DOMAIN}"
        hosts:
          - host: &host chatgpt.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: ui
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: chatgpt-tls-internal
    persistence:
      backend-config:
        enabled: true
        existingClaim: ${BACKEND_CLAIM}
        advancedMounts:
          backend:
            main:
              - path: /root/.ollama
      ui-config:
        enabled: true
        existingClaim: ${UI_CLAIM}
        advancedMounts:
          ui:
            main:
              - path: /data
      models:
        enabled: true
        existingClaim: ollama-models
        advancedMounts:
          backend:
            main:
              - path: *pvc
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
