apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:PBJgl6i1BEyyBaD0brxTMrkI/sn7WB0Qnn+NCwyvoNcpZ9UUAhOdHl5pUdpJJAAXcwCNWQFX/CClC6ENCjb8PQ==,iv:DNyRGgHUqaXr1raw8Dh3G/i9LIi4Zr4YorvVsDckrjY=,tag:MYQUlHnAirxP6vRfLz0mnw==,type:str]
    admin-user: ENC[AES256_GCM,data:1PR+33M=,iv:/d8Cw8M6wen1FzwD6jS0OMJzy4EcbQNlpB0xB00ahH8=,tag:RTtBSta212ZPxlb44RPIkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSFh0Z21DcXk1MlJBUmRC
            ckR1U1dNbEJ2Q2h5N2VYZ3IySThBWE00dUMwCjRwcTQ0NEdra3ZmUzdKaldNRlhQ
            N0JYSE9wR01jaDl2bzFqdGJqWUphUEkKLS0tIFpLZlA5cEcrdnZNN0E3UlZ6QWkx
            VXZNeTlkeTFkLzhzc3gzWHFrQVRSVEkKVZd95MkB8oXBk20vGqSd/qSY5bgL88eK
            R3ySQaLeriLyjxMuBWLbdkxqZjDPI6fdh1N0ImF+h2ipOU0Th72AUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:04Z"
    mac: ENC[AES256_GCM,data:pzXtqJIIxmqrOnVP8dFdytLVpPSLKB+n6bOibnvSIGmdZDPGmDGtkmgY+uqFrzgF2BSUY/0pKyWwVDGTc/zw+9Fs37dh8f4/GbbFQtLIodPrlZHQMlAJ5HkpbJIi4saMCOCr5nWzlfcXxVBsuBuH/W4w/eNxsU5sIQCEnk3sAQI=,iv:BytfsoCHrfdcXSalFFLXLdBwTt3HBpyRAH3yK0dcSW0=,tag:JDH6+ot/RFWGClZF0cz2eA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
