apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:/dkb3xyx0b/CXPR5MUTGvTjyl0fSCgs26OE8/ypZHSNSvMCj/LjBROeIBURa/krurIrXmy3Rmf5tJNVIokqNiA==,iv:caHOHuDOTjCQi/QCjStENEYdMAEdiO/UcRQT/H5upNM=,tag:MNSbdUCz1kc/CztI3xrG6w==,type:str]
    admin-user: ENC[AES256_GCM,data:s96ui+k=,iv:sApacAv/sP42cxecPHBZx/HU7XPgYwT0Q27C/ErcaSo=,tag:yMzHEzimQCdfPQPsL+jzng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMVZVQlc3dzlwYXVGelIz
            T3pCNHY1RklhQ3RwcVR2TXZDM2hEelY3dnpvCnNPL0lZOUlhL2dabFBCbm84TnZM
            RHM4bGc3amVZa05OdmNLRGhlbUQwcW8KLS0tIHduM0hsY0ExSXJrb1pxZjNLN21Q
            MmdjbWhya3B5bk9abnVsODZPSXRVY1UKU2Uhg9yeTd9kYUOgn8Gcz93Z+LnAB/AK
            pwR1n2ew49wywINpakdWt6sJbzQtSChakus52KlW+HTy7tssjzQ+3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:27:27Z"
    mac: ENC[AES256_GCM,data:UhkFp2LcYgecS9PYzd/+Fws392ScFVfLMZmw5u3usdqG/KuR7PJSjdnlWTmfMG0DPCsPhmZcxk2vcC2OF8BnGsdldmfxN/RpRR2r3ENI0Q5dFj4XJn7AOHjcIeMiwod0aLeauZG3GuXZZrnSMkr+8c8mN7yE94H7gyUKEEMIBto=,iv:cXHfGdR4+qzENfCKw4h5VP6U8eB1UXrD7C91CDpTI44=,tag:NBA9bZpJJFGB8J4GPsv0GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
