apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:Si3PO0sk6mh6XGnofmRGQ8LgpIU0LTaQ5LijVXa0cpmnQ5f3eGO5dGFWBNuZApeA1zWffGSu8qXOAVr2oMrgfA==,iv:dFVHc5pU1ajwdCN8BuAz0XwKCGcFq5f7UTDfIgM14/8=,tag:ClHbTMUjhzXRO4WKjJSUTw==,type:str]
    admin-user: ENC[AES256_GCM,data:3I0WEA0=,iv:/3I/oZzJ43CC0T+LZQNyc4EG2T9Nnf+oToHcry4wcZY=,tag:E/aME6QD/oavKb5m5ydl5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPck5jNUtQMmdrVlVHdW9w
            VjZRVTlGQVdacGp3Q09DSE5vblJoVVcvc0dZCm1jUXI1NjQzVHJVWHh4cGNjNzUw
            aVRxcE5KN05XRGxXbU5qaTQ4eTByVWMKLS0tIGw3ckZKSFlTYkJVKy9COU9HejJK
            ZDA0dHYrN3lBb1ZhQW1wZnlLSER6RGsKDsLZH3f5uYGHl1kJHM+ZmRYYptDY0/9O
            /zYBW5djWqz/1PdFpSAFIx2PKnU5FhG9VrK2xe97pzLs1FB+n/Ybpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:09Z"
    mac: ENC[AES256_GCM,data:1OuBwZWzhuSvBDyrlTznxCQc5J1NTH+WjoZrE419pL4ZXz+7Bkv9v8KAB6EALNZYLIz8viMB2pzO46a3/cX7M73Td4rw1OpLwlCEo2K7K9T8VJmGSLOzN7mSNHqTznSWvmrK6eEmCPdAIVmjDLBDTPnA2NpWC9fpvaNGyO07nA8=,iv:6XDRQcQExqhWYjMufUO4Vz0OVTrKV9WI4v+R/Fh6qLw=,tag:CP439m/5YhB50QRkwlAvvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
