---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: windmill-worker-add-docker-sock
  annotations:
    policies.kyverno.io/title: Add docker-sock to Windmill worker
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Add docker-sock to Windmill worker pods
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  mutateExistingOnPolicyUpdate: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: windmill-worker-add-docker-sock
      match:
        resources:
          kinds:
            - Pod
          names:
            - "windmill-workers-*"
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              securityContext:
                privileged: true
                runAsUser: 0
              volumeMounts:
                - mountPath: /var/run/docker.sock
                  name: docker-sock
                  readOnly: false
