---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: windmill-worker-add-docker-sock
  annotations:
    policies.kyverno.io/title: Add docker-sock to Windmill worker
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Add docker-sock to Windmill worker pods
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  mutateExistingOnPolicyUpdate: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: windmill-worker-add-docker-sock
      match:
        resources:
          kinds:
            - Deployment
          names:
            - "windmill-workers"
      mutate:
        targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: windmill
          preconditions:
            all:
            - key: "{{target.metadata.name}}"
              operator: Equal
              value: windmill-workers

        patchStrategicMerge:
          kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: windmill-workers
          spec:
            template:
              spec:
                containers:
                  - name: windmill-workers
                    securityContext:
                      privileged: true
                      runAsUser: 0
                    volumeMounts:
                      - mountPath: /var/run/docker.sock
                        name: docker-sock
                        readOnly: false
