apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:53aqEu5kKHMx02XaqX60W3bVi/UTZJ84,iv:h9WiuIRrawK1K3VuQtr/4r/YGVivdHQUEKGudK0LUxA=,tag:FEAi4wIp54TasfZsf+lcfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvemdWNzlLNWNqcVdTc2h4
            TmZzV0ZFdlJEZTBPQWQ5MmRqUTNIYk0zOGcwCjBJK2h0M3FyVG5GMnBaQWRhanBC
            dElDbGFmaEVOYUxMN2RPS2JrQlI0akEKLS0tIFNtcmU3ZngrZHpsWng2WERJbmRM
            akNOV093cDBpOWcwZXZqelhCdVl4Nm8KlbyOz7n34j+xP+2L/mQiKpnLlLB9BS5S
            lcNFGzKjDlvgjGgVfgQpME6Hi/tbvWTrNmiM6B2l0q0vPB7wY/GGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:27:23Z"
    mac: ENC[AES256_GCM,data:DsTkTn1gQgbC2J2SmKtDIfb+QWvW+8SmQNptIRybHN+nTCXjF/AA2pTsoIUib+mULp2gKSVmFuX8uAQMdjF3we5RtEpSUMdqMVllz8tXVc4xzBcZmX32QJ3osckyVz2Q6uPih9fOfaq8YF9FhlKKYLR+3GQNvHm6HbyBGJ2DrtU=,iv:+QK59cU5H767M2Wtpsg3RbbWeoAKq9zyGEj7gIJWTMg=,tag:updHsmpPq/Q/L15YyWGw4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
