apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Sjh0T9GGDoIRjZPgtpSgcY1GhmydZBm/,iv:ezZE4yJtQA9v0/BsPNmTzTqSSc9sUDdidXadDQ88zoo=,tag:7NyoDFEa9bjcCti7ErOiLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVHV5U1lFc3F0UE1JUEpQ
            bkZQTTJ5SzhRWWZZbGxzbjJLblZRdDVlQldvClEzQUlHMTFkaG5NRmdFNkZtT1Ji
            UmllTVR1ODl3NjVwMEVCZ0NLMlBkNHMKLS0tIFg4VTdjcmtxK0JBczBxeEFtZWZW
            RncvcGNzcVNnT1hsUkJkcENlY3hvUDAKrThGp6CFPdV45ZAWVEZSHPgM/NJU5Zpt
            6l8SPWjDjZeSauSsIyZ3aB3jVpnUFkIF2e1mzbJRv23eWXqA5cl1JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:00Z"
    mac: ENC[AES256_GCM,data:aXnON1zSE3NDUDK7b86k6g1sDgdCHrWTcPqrGZu9vgBB72/i6T0+GIdDXtyHaHl7A3qb4tD8UPhBjSFLXVe1bUDubPLJUfntIC7hhdXVbSwoGemYdDySWr+VkRe0+dyiKm11P3VeMqfZP1BDf//63f+xDD1VwoOHbsY8fJ/0ei0=,iv:+hIE8X0+n25/MXbnUoPeZhF2CZWh9qy1DeHKEzIpqt4=,tag:DWxPmZOivhVSwNHntKdvtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
