apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DM04ksPdvJhCr1Ugng8kXhcciHl73mrE,iv:Wp7HVfVfP6bKzlWSStnZaUkHwdDL2YzMiOMFHr1g+Kg=,tag:aFm37KIBm8Zo8DFznmyGCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUnk4bkE5UlFSRGk5eUdx
            c2F2KzFCbldJRHl0NFk5Y2doKzFXYTJqVWpZCmtTclVacTFvMlhqandqellEOVpK
            bndCUG1odTVERkRxbDRXSytKNjMvUmMKLS0tIC9rV3FzbUo5QlJZRVY1TGFGUXJm
            NzR1Q0xmTjF1OTIwWmNqRDlOMkJZbncKgSdz2noE+YJE6X5OnCqUO7be5Whci0DQ
            0dZFK2v6P/9wbmvPMJjNIsWUWsQpHL2GpYojiNMHKyYgMyYzHHl+ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:05Z"
    mac: ENC[AES256_GCM,data:4PnI7XtJdBMl0AGIY2f/Po9vZBwPuZ5fJef/OLQ4qmXOxRjfTLX/lwQPJpnzBvEghRJshfd6Th4lj3ey+VNCZLkq3ppTu/F4CRd7AQyaK5TXB1x0B2Gjj2vzf/mPUva6XBAnIiQmoTGWtzUA407o3EnHf1aUCyTN5/bWB4o3eMg=,iv:vgMnjzy6N2tLltKiTUNq9qmuiNmWqkeoMZQNRYwjhW4=,tag:FRIt9lK8XRe+VLC9i4KCWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
