---
kubernetes:
  children:
    master:
      hosts:
        dwarf1:
          ansible_user: billm
          ansible_host: 192.168.134.11
        dwarf2:
          ansible_user: billm
          ansible_host: 192.168.134.12
        dwarf3:
          ansible_user: billm
          ansible_host: 192.168.134.13
    worker:
      hosts:
        dwarf4:
          ansible_user: billm
          ansible_host: 192.168.134.14
storage:
  hosts:
    dwarf1:
      ansible_user: billm
      ansible_host: 192.168.134.11
    dwarf2:
      ansible_user: billm
      ansible_host: 192.168.134.12
    dwarf3:
      ansible_user: billm
      ansible_host: 192.168.134.13
