---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kavita
  namespace: flux-system
spec:
  path: ./kubernetes/moria/apps/default/kavita/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: default
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: synology-csi-driver
    - name: volsync
    - name: external-secrets-stores
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: kavita
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_STORAGECLASS: syno-iscsi-delete
      VOLSYNC_SNAPSHOTCLASS: syno-iscsi-delete
      VOLSYNC_CACHE_SNAPSHOTCLASS: syno-iscsi-delete
