---
- Home:
    # - HomeAssistant:
    #     href: https://hass.${SECRET_DOMAIN}
    #     icon: home-assistant.png
    #     description: Home Assistant
    #     widget:
    #         type: homeassistant
    #         url: http://home-assistant.default.svc.cluster.local.:8123
    #         key: {{HOMEPAGE_VAR_HASS_TOKEN}}
- Media:
    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.${SECRET_DOMAIN}
        description: Subtitles Management
        widget:
            type: bazarr
            url: http://bazarr.default.svc.cluster.local.:6767
            key: {{HOMEPAGE_VAR_BAZARR_TOKEN}}
    - Prowlarr:
        href: https://prowlarr.${SECRET_DOMAIN}
        icon: prowlarr.png
        description: Movies
        widget:
            type: radarr
            url: http://prowlarr.default.svc.cluster.local.:80
            key: {{HOMEPAGE_VAR_PROWLARR_TOKEN}}
    - Radarr:
        href: https://radarr.${SECRET_DOMAIN}
        icon: radarr.png
        description: Movies
        widget:
            type: radarr
            url: http://radarr.default.svc.cluster.local.:80
            key: {{HOMEPAGE_VAR_RADARR_TOKEN}}
    - Readarr:
        href: https://readarr.${SECRET_DOMAIN}
        icon: readarr.png
        description: Books
        widget:
            type: readarr
            url: http://readarr.default.svc.cluster.local.:8787
            key: {{HOMEPAGE_VAR_READARR_TOKEN}}
    - SABnzbd:
        href: https://sabnzbd.${SECRET_DOMAIN}
        icon: sabnzbd.png
        description: Usenet Downloader
        widget:
            type: sabnzbd
            url: http://sabnzbd.default.svc.cluster.local.:80
            key: {{HOMEPAGE_VAR_SABNZBD_TOKEN}}
    - Sonarr:
        href: https://sonarr.${SECRET_DOMAIN}
        icon: sonarr.png
        description: TV Shows
        widget:
            type: sonarr
            url: http://sonarr.default.svc.cluster.local.:80
            key: {{HOMEPAGE_VAR_SONARR_TOKEN}}
# - Calendar:
#     - Agenda:
#         widget:
#           type: calendar
#           view: agenda # optional - possible values monthly, agenda
#           maxEvents: 5 # optional - defaults to 10
#           integrations: # optional
#             - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
#               service_group: Media # group name where widget exists
#               service_name: Sonarr # service name for that widget
#             - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
#               service_group: Media # group name where widget exists
#               service_name: Radarr # service name for that widget
