apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:UvBDrGMzkfX4+2oNEXQalX+H/T/0KiTp0FGlvPRrnsq6GaWwp0f5Sg==,iv:Nfb7XJK5rY1bHOD3BA+M+lAPqwAPoyyj/OhtEgh8FvU=,tag:fLOMBqiGVNWZVzbv2H2mHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S2QrZnpnbHRHeEEvMTJh
            VnhQUC81SGQ0UEN0d1FqdmFwTEhBd3B2UVRzCjdxQ09TWXdzNW5FdW5YMWErRC9P
            TVA3Q1I2a25VZG15VE9STU9jY0RJc1kKLS0tIDJzUlZrT0Z6UUtQL2JKL1BKT082
            djRiYzRSTUI2SkQwSWxpc0JlVjRaa2sKfZgq0u260nKk0T6kf+Xzg+schktQI7VX
            GMkVIQhWqseTzXbNpcHPKoakt9FF3NORp9SjH1lthRJb8+QajELj8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:27:23Z"
    mac: ENC[AES256_GCM,data:D7gIZQoOOXDHwntjOy2ICMGJ3O2jVpIDW+xS/brs04NehhApndbck1YXH6YF3QPFXDqpsrPRGYoRVY1CgXHdnOO7HGpwYJd7KXJ14Wsp+xujUfCz6IomH0GN2HLCxCebKONiqsWO5ZxWKYUCGsEecIA4F9aHWt8EoPLMdFJPkk4=,iv:g7N1bp937yZYKkwYTEEwdSrFYYkkVAGu0cm8ALkKZLQ=,tag:uqBe5FtkKhkBA6CrjWdRaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
