apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ESLLbdXVgojRBJukYzIHuFjyjfLKesIC9kogZPpAo/m6VOzl5cvEmA==,iv:hm3COdgmvku5/0NVqIXKvDxCAZVSNI3e/cIOW0p8ez4=,tag:yG4qeNKoGSR1hSIwnHYLqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbmtmQ3pzZXlGbXRad2hh
            bS9NdVc2c29sZFhNT3VhWldxRVczS2hXVlFJCkd0UWpoMlA4RW1zUWIzVVZTMkxC
            cUtqVE4yZWoxWVk4MEhzWkhJVGdaUlkKLS0tIGZlSnA5am5rdUpCMkgwNTRscENi
            YnNiQ0wwb3BxRThBdTZGU0lwRzdzaE0KEW/gIA7aC8ejb6X0E6XIQcJSK0Qy1UVs
            YqEx9tdkMwPBysRbS/93qfDHOlCR9idRCRTAXLyqFyfFGJDeBF3tqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:05Z"
    mac: ENC[AES256_GCM,data:PwRm8El9E1xZWV8C4lMEv0CsmpKbANwf8W+rLsJOW4mVeHVNFymC3xCRaGGDlJWECnkLJTTBSqnjqqBQSIQgyAVAu0eRPLOlTn95oWXEb2wZ5OGpA9AaaSQfdX/Ip569BffEqhMmWFe+3Z5ChGU7F8YpDonI8EZIcaN7HP0mETY=,iv:aZ37SWgadLfKmK8la1TgMF/h0d/xSbb8tikbnDfE/vI=,tag:rf7svKO/lYJiyAiVoEqDjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
