apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ZQ//mRrtvzkm4BCvlV8TBeHR21giQvVNUev3+HgaZbEOODQN3xd5sw==,iv:cmqEBnfERq+9qQRTL6VUYN8BlPuvzK+t/sgjPNfUF/E=,tag:ji5guqSLCNlAFCqgk+XszQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONkhBT1BKYURFVUEvOTk0
            QjF2QnE4V0w5WXRtcWQyYWVQVDhUTjFFdHhvCmdpakdSOEVNVklsaGc3LzJwUkZ6
            dGFsL1hvejViZlJocEhlZE1kOVRub2cKLS0tIEVsYkRldFUvdzdZL0JJcXdrUWpO
            clh1L25HY0lIK1RNL2FSZXlVRmVIaGMK4y32SRPVqmOJK3ucDpKOeH3zTTaI0mQI
            FqOVa5OOvW427L9U3MF7O2DukS9cXR2/fjTecsneNTNpwSWC7PqwDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:00Z"
    mac: ENC[AES256_GCM,data:F9sBZqpxuBOBDfKdaDHj0Bo5igr59pOtQI3w+U1Y+/u6/ODclDnteebVKfXqxAWE/l4VD9aW6Xfl8n7AoHyDTed99BYYCtSe7PZk5ZmHTSX5CJU5DBBWNZ+4zi8Ya3alqTXEN4xCc2idzYAla+QCcqpmOS/7jNb1ol5zR08fagE=,iv:O7Mlke3TGJcGJcyB+Fgjer+CtlCnIBHqGDPYk3U81E8=,tag:WjkuYmULRy2aBnlAseR5uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
