apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ZKhUiYI9O5HDEiKjxpJqq0/7hw8+m3NUVH2NLQ4ao2K0RkJy4mrFgw==,iv:k5VN0WmfPnmCUcVK7EOnrMSsCHVB18DYlRHqoBfdnHA=,tag:1c5tkDUsoJVPIh/42savZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOHJHYUtYLzZtcThXRExE
            NXk1NVYwYkN5L2J2cXF4cmNsanpRMUlDblZFCm1qWHdXZXBRRERMUTBlMFlXbDN5
            ZC93VHhJSnhvRDd1RGlaaXFzclBhZFEKLS0tIFR1VjUva1luclgxQUhXNHBrUmVV
            L2NPTnRKTlMvMHhOaFEySFRrZEY3NHcKMcbHHXdEJ1ehjHzXuavdRPFD3PnnFE1s
            Ih48ZlS/+e86WBPVTCQuHbLgvEwf4uRZujcmrDHCUYUrYUAMxAGA1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:00Z"
    mac: ENC[AES256_GCM,data:STe5mTzpweVf2wNn0hN7Xt4gvjduCtL+vmKuC+GbVN6CbsaF0LelC24wp0i6c46Can79/UEMylJVhiTKpgEMhmEvFBenlfXqMzJLrJNEofpcRseTsLAzN1GUVTDoz5M+dNlXIdTGgDX4AoVqpfn+TV2JTef/HIX8m5aMt1B4feY=,iv:OemQBiz2fXvpUgbv0w0lDcxbBwds1YW/TJ5LVzqOZso=,tag:n/j1QF4QJ2qFo4wpyTeCwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
