apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:Ebaes46P61/etoPg1O0rRyRjapnF7Sibkv2MKOJcUdA3NZKm2hEHmQ==,iv:NAvc7K3AMXQgTAveKCKDZybt8Pn+a9V9XTC4/laU9+U=,tag:0Lr2x6dluDlFRXiLNOamxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCelR2cUx5eU9nb3FTKzIv
            Q2VLNkJjcU5TRmlwVnA3dUhRQ2JFR1BYOXg0CmVOVTdaREloN1hCWmlNVHoxMkpF
            cWhIL1Uzbi9ValJldGpkNWZFaE5rdTAKLS0tIGl2VS9aeU12MXdQVDVHdi9aQVk3
            dWhpdU9GYUtydzV1L0FTNUhoQ2tNTjgKoOc/bg8QYtXrqN+LplswKuB5CJLxybw1
            DVZOxACEv/8lnL/cIiO3wHPZzVcn7GB0lc8g9VVSV3RrmjsLKlbZzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:05Z"
    mac: ENC[AES256_GCM,data:f9mFKMQfajcptkmcRWa7ByPOTPHpFTdlcGvdhR8ncg8yEmq7lLAai2Z6B/h3UPdX6yXT1rIZLPcU11/nqs8m5Wxj6shIzdQJHg80dnEBjy4L+uGBdQ23ohg0i/qaKEwAswSL4Lr4nPVToLJcVqVy9zfu+hm1MfnlUVT1xn1sNK0=,iv:cZSKi1Jjikh1034JCXrtJgZOR/XrszAhN7WBmAA2uaM=,tag:0/kIVumvr9U6v5RLWgTeBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
