---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valheim
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: valheim-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: valheim-server
