---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: windmill-worker-add-docker-sock
  annotations:
    policies.kyverno.io/title: Add docker-sock to Windmill worker
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Add docker-sock to Windmill worker pods
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: windmill-worker-add-docker-sock
      match:
        resources:
          namespaces:
            - windmill
          kinds:
            - Deployment
          selector:
            matchLabels:
              app: windmill-workers
          operations:
            - CREATE
            - UPDATE
      mutate:
        targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: windmill
          preconditions:
            any:
            - key: "{{ request.object.metadata.labels.app }}"
              operator: Equals
              value: windmill-workers
        patchStrategicMerge:
          spec:
            template:
              spec:
                containers:
                - (name): "windmill-worker"
                  (image): "*"
                  securityContext:
                    privileged: true
                    runAsUser: 0
                  volumeMounts:
                  - mountPath: /var/run/docker.sock
                    name: docker-sock
                    readOnly: false
                volumes:
                - name: docker-sock
                  hostPath:
                    path: "/var/run/docker.sock"
                    type: File

      # mutate:
      #   targets:
      #   - apiVersion: v1
      #     kind: Pod
      #     namespace: windmill
      #     preconditions:
      #       any:
      #       - key: "{{ request.object.metadata.labels.app }}"
      #         operator: Equals
      #         value: windmill-workers
      #   patchStrategicMerge:
      #     spec:
      #       containers:
      #       - (name): "windmill-worker"
      #         (image): "*"
      #         securityContext:
      #           privileged: true
      #           runAsUser: 0
      #         volumeMounts:
      #         - mountPath: /var/run/docker.sock
      #           name: docker-sock
      #           readOnly: false
      #       volumes:
      #       - name: docker-sock
      #         hostPath:
      #           path: "/var/run/docker.sock"
      #           type: File
