apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:yzEX5omgBrX3CZh4EmU+/xoIpZM7RIdul0eltTptcW9sYU4Y6jtQNCwm87amBKeflNrq9E+Owffyr5+X,iv:3aa/eh79PKJYVJZsrjJ8WQWkLncqxZq1YsZRTZKq19M=,tag:k5/ZT4GV3Z2s/C9pRR0ISA==,type:str]
    username: ENC[AES256_GCM,data:8Bcg1G4=,iv:6b/Io/joUhju2dwrv4ddIyfz498A2hGyYH/sMdi+ylA=,tag:W60MjhIMXiqIGivTeLp5yw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb1U5WDR1RTBnTHJsVVhN
            bUsyN2YrMGhnYTBnQkcvb20zRDRwd3kxMVY0Cm5tVk1ZTEtZMldmZzJ3MzZ0RmVs
            cXZwanE5QmFxaGlyeWF2K2RqOU4rOXMKLS0tIHhNV2dmNmZCa05WeDUxRytTdGVt
            VTQwVXdtMklnRWkxaTc2RG93NWdzaDgKumtNUhAsb3ahZxfmpY27mbRdpQvK6uVA
            WVPfnWxfEJvE7T8dQVttBmJvrZykGWHYOF+UxsHlTtCJjhJpHHljIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:16Z"
    mac: ENC[AES256_GCM,data:6vt/blF8FK4t8HccfQJl/HEizdhpuOwCcXBBXJ4KBKeXhOz+Ed7A1ibfGJsmA/rewbT9qZS172+HoPzn+EyMtUstEUWVEUKJQZrG5zRvxU+Muedk34PoKAIG8heoo3EVBUvAelyHsfHCl/RIveew7/v1VLXTcHOWv6fZxFABNhI=,iv:QbaLP404KiTtIWV4qoLySdCLi817GAt5DMzU/RlB26Y=,tag:JQkoWkPUQTyxQsAra20M2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
