apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:cvhfwPRr4AgN0zXdtfeBagB6eKCnOsVSvNzjrXLX30p9htm4qmh0Qq2yStnFS4SfCt97y2tjB+yJT62w,iv:8jxRnMYvj5+kFdS/SA15hFrPiC0KfL5Yuc5emZCoYog=,tag:pTf1iakdChj/Z1HBoFZBKw==,type:str]
    username: ENC[AES256_GCM,data:SCGIqdY=,iv:2dqCMo0uTnG/uorbAalYFgmiXz7rwgI/mllCR+Ru0fU=,tag:bwX3oa0ABKtPzsWZsTzGEw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXh6a2tleGFEKy9GTE9y
            YldxLzljdXdNYjdmb09OdHVBY29jbVFxVUY4Cmt5aFM2d29Qbi9KaHUwdDhXVXRV
            UmlrQ0NxaTBYeVNmWnFsb1FLWS9yTmcKLS0tIGlxeVZoSllzb3VPQzBPdlFLeWIz
            dStnYXlSTFovcjgyVUYvOW5scWxJSkUK6ShFxQK4M1olP6TnWdX4TA5P6pOTBquG
            9VnAhc0IO9Wf6lC9R6HYMznTUgnCgMINiH0Odch3jmTpvPxOWN4u5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:12Z"
    mac: ENC[AES256_GCM,data:94kmzPCnMrIm9C1SFmReckzMLGNQDzic6Z+bpmSErjKvGsXJ+r6HRIDem1twlEbTsf+wGXPcWfUMHwS1baNtxbv9H/f7H3Q6ndQEH88wUJW7N2dkPy6IHLLsBJkvzPzk/ZYJ59jkNs8CSv1FHlfQDtcw89IDFKkV3hUqUfoIwns=,iv:MxLz8d8oOf88ysiSboXAI6U8EkUqDaekQQCRDJ03lDM=,tag:6FuhJfE1G1PZzpU8nVFx0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
