apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:uJbAEaORZQLZV6dJu0/GdDBPJDa/HTCDHbPTYjaJsx3z7HLj30HzZf7yYgQ/m5XUwh9jLpEP+FMe/WzQ,iv:ws+Mdyb1RpaerVxaK0M6G3tdrNB6x0hX8nO90vryc4c=,tag:pdbQ+8NOKvEuhDf3EhIstQ==,type:str]
    username: ENC[AES256_GCM,data:gbwn050=,iv:oD/LbDSK0mZdS8zcp0yeaMV6CEzjc5FJ92KoZ9daX1s=,tag:mWa65xlaVPvaMZAJrWLmTQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WE9BR1EvMnJmOVdRQnpp
            a0pKTVlFOWY3dVU3OW1kYU14MWdVSjY5cnk4CkZEN25wdFJTMDZTK0d0dW9uNi9Q
            MkZSUXNrcTYyWVZDZU9kWUlEbjlZbzAKLS0tIDU3QWRmeVVTeUw5MDlsN2Q5TG9P
            ZnpCU0VIMWpPL09kNzU5VnYrRHdXTncKG/ldgNLZ+NQpZ1DSgekHDZCubEAQZ6bz
            0KPeGCDN3fljgpPDMf52+0BrWMxrJJ+QyJpSEy7KCnp6AQ0rWbLnVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:27:35Z"
    mac: ENC[AES256_GCM,data:wt0gcDbMMu7XmGrQi+7e15bgv51C6mt7Pi+rDl9MlxN9ByCJ9Nl2ZGfvVY8FX1UNneBi6BzsmBKto0PaholyIwuVug2kR0k/5zldaPlTFuJf5freHU8TTXjVQccj3P7viet+LgTLN/y9+CLG/2X1wN5Tp6NxEApu6u8SSI6blwc=,iv:yABLobsicz+fbHRWBSr+jhbuWAb03PxTl+Fxc0BewsY=,tag:WI8xcTjZQkP3l7aBIuBQIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
