---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app n8n
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/n8n/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: default
  prune: false # Should be set back to true after migration
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: volsync
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: n8n
      VOLSYNC_CAPACITY: 2Gi
