---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./kubernetes/apps/default/n8n/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  dependsOn:
    - name: volsync
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: n8n
      VOLSYNC_CAPACITY: 2Gi
