---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-rbd
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-cache
# spec:
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: syno-iscsi-delete
