apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yjYZ/kJvi8lv,iv:thTjAfVTBYEmdcmMSQTapb4YWSz3SlrtEqR0kfIwpck=,tag:zwIM/pMTB5MEfDTGlVxEKA==,type:str]
    SECRET_LEGACY_DOMAIN: ENC[AES256_GCM,data:ApCDVuc+ACtYYJO3AMk=,iv:UDDL8NOsUJsLygSG6MuOc4yZtp1rU3iXMU1T8XRVpH4=,tag:wH0Yd1Zcpl/TUDmmd7Av5g==,type:str]
    SECRET_BUSINESS_DOMAIN: ENC[AES256_GCM,data:Th3wf50Y+R3dglIZMmX5DiQ1rg==,iv:xoYud6u4+/UK2nLtsa+pACQKTz020toOjWn8D+Iugb8=,tag:+phIirpfCUjxtxNbfCR/Jg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Uf8BuhyHTdG9gdU1ecq7xQzptQ/fgy8npi6YsWvU12qcEw==,iv:ma3p+aJs1G4Hkh/MO72xabbPm00x+8PuZp605Xd3qj4=,tag:T3GY3VCtCVtNU1L9lDhTkg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:A+S/zfV7FS14ygRHVDTlwNsUqB8gH4pqj3k5QhSB+KNZYhk3,iv:rp7/sMjP63z7cddxEADj2JSshTwOs8/9tUiKBjLEvqM=,tag:EAc6TLACvZHhazNXHCZu9g==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:J0VP8HrfPdBfKRkHScSVw8jpHbPFzCxjL1p4fVg=,iv:DJGmANbrenXc/AstrzOQWSyUjVqChMt0tULVtUdtF38=,tag:xh+mOpI+xNwjw/ELw68B8g==,type:str]
    SECRET_LATITUDE: ENC[AES256_GCM,data:K1kx9+JUDKoKBw==,iv:TMDoDblFHFtCbPxDTTHj3TsrSJPlC4tSMdPORtU+S9g=,tag:r9Eg3Rac2DlKvETE7l83Jg==,type:str]
    SECRET_LONGITUDE: ENC[AES256_GCM,data:y67UvSLgN/RtowE=,iv:TjGEQaxQ9YeKvO7UWU6J/YwarPKgYXWjRiElKVftxlU=,tag:w719lO4jIEZeAm1dqdQNrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xgdtxuz0c6636aqzejt63kr0p8rutp6m0e6nmagnufc6mj5l0akqtqa2v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNW05U1hyNU10Mktlck1r
            NUZUNjlTeXlaS1VUQkI0d1p1anFLL2RhUlgwCkVYdEc5RGhZM2lJSVpHeVFPWTND
            MHg5bkVtU2dLbTZHeE5tL1ZJdG5KQmMKLS0tIGY2UW9tS0xMWUNFV3JpaGZCeGN4
            SzVNazYrZGQ2RFdSMzJSTjI4b0VEd3cKnRl3+Sf2Wiq6/Wvs0Y9ckU/RfrpP6TB9
            iUAUUKSHM7erhHNYrPf+Zf/uWTzVAkyVeaVQAvDe3uB9WmDfUuL7hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T02:54:36Z"
    mac: ENC[AES256_GCM,data:u/fpgehD3a3pbtvyw49tAO3tuCPxsIwrv4uJaB2Y4DeZ5V3pCQGJuR6xuJbOmLKfc9LR6zjmtNK+ChvGge05zbLrB9nt1eyaQaxYN/SJWXaY5lc7AoQHjm4zybEPFkbFjgozTlRX+3ZWDMiZJhHuxv+DXWdRTvgudRYzA1XTVts=,iv:hYCBBtVFLnNMYhWzlwDbPqJ0TnVYZkyFTeJ6OAnlWGY=,tag:DdXwr2wCPOYQnJDC2D0xkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
