---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # Common configuration variables
  CONFIG_TIMEZONE: "US/Eastern"
  # Service IPs advertised to BGP from Cilium
  SVC_GATEWAY: 192.168.135.1
  SVC_EXTERNAL_INGRESS: 192.168.135.2
  SVC_INTERNAL_INGRESS: 192.168.135.3
  SVC_PLEX: 192.168.135.4
  SVC_POSTGRES: 192.168.135.5
  SVC_VALHEIM: 192.168.135.6
