apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:KYt+7Ti6Xqv9bxYe4D8DKFOZsPAZWuhlL7xGEv0=,iv:E+boMYsO2ZN1KYWNlSpOCPzILgnjLxOz9JSu+A9KQJc=,tag:hwgf/mgRTxI73KxZM72p6w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yD5busKbriney72SN1/gzC8pqns43AHIYCXllkrnet/CYzGM,iv:hSIEjwBo287mnInkSTTDM+UsL6UyTL31rtzPpfQsX8s=,tag:GHsd83ss0awHU//wl3RvXA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:xjHqlgiWkxLW+9i8YTs=,iv:TARaWJKVuc70Jg3f70qPc9zTvAdbxFiZ9j0Wzq8inKw=,tag:IrE0MWneS9nyQQ/gFhOMsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUnhDV0Rpc3NUMitCM2ZE
            WlpWTzRvNDFaVERDWE9WS2l1c0J3RlF5U2xrCjBCdXNUdElYa2R6VU05Y01vUVE3
            eWh1ZVIzd1Nhd3lVWUVmMytXbmt5RUEKLS0tIEZLVmN5R0dmZ093RTJqenZoSGNy
            Q2VBZXV0MldSWndwS3ZiZEdFV0U4dlUKXs9COrPV9jB1Yx5IgfNKy5OprKPZjXoQ
            lB2fufUDA+Xr2bqnTHT/PW7zlgav+lldyYd0SBfYNurPK6MgUhiGKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:27:22Z"
    mac: ENC[AES256_GCM,data:qCIOfJV/Kp9/rDVugOcCI7VnDw/jVkOeNK2oeXcL5E2c7MpXoHbN+gIbS9akHnblEWB5xBDknksD68/1OlNfCH72BDa4eQBzar6h082Y9OmxH1HhF0TvnIyZxfTKMUEDhdVDIpHbVEp+JXRTeOaFJqX++pnjNPP9drdR80oFiFY=,iv:ec3wwMac6A0cUxxNTuu4mz78N6ARvp7ARlNt+GZQoaw=,tag:oWI4K6h/6LgNZphHj7ejIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
