apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:t/KRuMILMkrRzL2K3JLzjMeB9xwVQgx5FR2mJ80=,iv:owDS49m5/zpxwnmTDvNlNotGleMkcbv7KhcwisMwXzw=,tag:+HegGaZdNHSnyUzAXMQiCA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RXtuXwZG3zFCERjcrLZlXyxEWzlR6EFzI4BGAC/RBUV2xcoN,iv:phHN1Jh33r6/1AK7MqLgX53Rmpl9ngtjFyndOh+Rp9A=,tag:zXG9caQqfWullIA/eW6XtA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:aNq6Dz+N4O9agTw6vUU=,iv:/rHsgZ40GwxTMtAHqXE0hxHSv150qbNOXXBcmDySAyw=,tag:R8GkC2u6CsE1K4GKBT8Z8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYVlUR2phaEdZNUJmdDRp
            L3lVanJJNHRmc29mT3hzb3lDUXZnMVduakF3ClpnYUJTOXluc08wWGd3U3l6V212
            Z213RUpZZk16MW96VTkwVHJQR21STHMKLS0tIDQ1R2pUNmJnMzdzbENHNzNqRjNJ
            UGM2UWp0RW5HdTcyUTFpaDFXa1BuZ0EKkezYRkDyuNtLj0UAEhvTiMuGXbeID0yf
            +EZeSmToZbxf4Nxo4dcS9iC07l3RkMCGN86TctRgcYuclDKRbEzbVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:41:59Z"
    mac: ENC[AES256_GCM,data:zXTYqjgFGlzAacmE5c6eB14BkzyWnUOZGR9l62Avp7524Ai15iAEdc6oO3IT43/ERxUwQDwaZZsY9xVuD3wHcLMjnG8HUw8oPJUue96+OwaMCkWibKDBTPSqbSmJkOpRoa+jgCBoWgnq42m0SQ2wVimFQIGSjSEyzUT13umKuHY=,iv:HSxaZurWUtd5Q6OUT+mrG4Rk8VcPCc6AfMft/HtQoC0=,tag:KC6storYyeqinb6a0CPmTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
