apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:x39qF+2DJZ3VbNi5,iv:YcmZ7+ki9cAgpf1ORWOtEEp4oAngshopRPebiNyUEGc=,tag:e+CpO9U8wE4frsnYDVgzGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTHU3b2FERmJnaWNuV0tv
            cW8wVUlXdUkzWCtMVG9GbllKUEUzUnJyUTBvCnEydis3UElWM2J3MVM5clNBdzJn
            TmdHUDhxQUJMQXVtTndrK2YvRkpzcnMKLS0tIFY5N29IY2dEOU1CUTU1VU40Y2dj
            MS95MGdtNGcyY3dIaEhUZTI2WTVqWlEKQvyIGXIowfhxOwQcdq+ZQyjIojodXVqf
            Mohh0S9Bzt2AdSfwd2W8GdZ8z68r75iTKWTfpfHT24k4Crf5GAmR6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:04Z"
    mac: ENC[AES256_GCM,data:p7JLWH3oj+S0RZxIeq8hfKV2NAHBICimfKAupmnJIZNu1eBbQwb1+nDNPG0I1Dyq7SoIrq72P6o3LnBg675MbzFeJlpEC0D1bH7kNc5/znB5Fj0NxVDc7YYzLsfnPRbBNtLx7af5wCuvmi3FKyvpzoBQajAlqO2OzHqnVJp8fCw=,iv:2OT9bOQAIr+5zkKjK9ShoUkOvOaGn3MBLJQrb5y325A=,tag:gIRko+9p2fZ9qvBS15Et9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
