apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:lr8oIBnnMdJsTAdu,iv:uAe0OZf2b7VVmSdhBWQ7sVJ51AZgxmsVvwndJjU2Gws=,tag:EqxS4ZBnCDvcDB2I2II+IA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb2lQUGRSdkszNk9IdXBs
            UzFhREVpcE9HUU9zSHZwL1BQM25mR1BsMUNZCkpXWXhHNmY4NmJRZmFCdWRQZlgx
            Mmsra2lQdHBodHhHbWd6RzB4aGZrTjgKLS0tIFF6TzBFZXhIdTJwbS9ac3RYQTAz
            M3lDY2QxdWh4MHJVT0Q2b2ZlU1duUEEKKOqi+uhe00vD/KOYoWYMuYbEvBWFg94N
            ieGuI5rONdiqn1Uq6GI3RdmKcc1pDJDiYajQIXqBla0nUG8JBmyIFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:00Z"
    mac: ENC[AES256_GCM,data:lu1jhJFKZbiD6SLdrPPGDf3Sh+REjKgv+7B/aOKH47vgE/k8d+LvLoarER2DqZSlpxWtU+UhNwG6rQK3BHoL3nC75xp1uG/OmJMtZ0TWHpwQ7u3FZ4pK877E60xw6cUjXsoliETZomKPrXZP1u/J+zhcycGSTbGdn4FAV9SvG20=,iv:jd15KPt+RuCIVUkdPgTiQU2+2KS7vj/qbl0IGdoAFSo=,tag:NONnVZ4x1s4Nqa6Q3XgB2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
