---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-user
  namespace: flux-system
data:
  EXTERNAL_INGRESS_IP: "192.168.134.65"
  INTERNAL_INGRESS_IP: "192.168.134.66"
  SMTP_RELAY_IP: "192.168.134.67"
  POSTGRES_IP: "192.168.134.68"
  REDIS_IP: "192.168.134.69"

