---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hoarder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hoarder-secret
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .nextauth_secret }}"
        MEILI_MASTER_KEY: "{{ .meili_master_key }}"
  dataFrom:
    - extract:
        key: hoarder
