---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/moria/apps/default/pgadmin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: synology-csi-driver
    - name: volsync
    - name: external-secrets-stores
    - name: cloudnative-pg
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      # pgadmin container requires uid/gid 5050
      APP_UID: "5050"
      APP_GID: "5050"
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_STORAGECLASS: syno-iscsi-delete
      VOLSYNC_SNAPSHOTCLASS: syno-iscsi-delete
      VOLSYNC_CACHE_SNAPSHOTCLASS: syno-iscsi-delete
