---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./storageclass.yaml
  - ./torrents-pvc.yaml
# Media mounts
  - ./movies-pvc.yaml
  - ./movies-unvalidated-pvc.yaml
  - ./shows-pvc.yaml
