---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Apps
  - ./hoarder/ks.yaml
  - ./homepage/ks.yaml
#  - ./kavita/ks.yaml
##
# borked during csi migration
#  - ./librechat/ks.yaml
#  - ./n8n/ks.yaml
##
#  - ./open-webui/ks.yaml
##
#  - ./overseerr/ks.yaml
##
#  - ./pgadmin/ks.yaml
  - ./plex/ks.yaml
  ##
#  - ./prowlarr/ks.yaml
#  - ./readarr/ks.yaml
##
  - ./redlib/ks.yaml
##
#  - ./sabnzbd/ks.yaml
#  - ./tautulli/ks.yaml
##
  - ./valheim/ks.yaml
