apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mHVniaA7ccJ/JGmmDIIost4OPucR4gW3GFljYdENTFAANkSa,iv:1SmSuhBFqHufIBlbNOvbDAR8Vm7DpFoEvb+E2FjMn3I=,tag:RqZDtKT185I/p+7yG8e9Nw==,type:str]
    credentials.json: ENC[AES256_GCM,data:7detIJiVTQ1NPPIJAtNN3otVqjRNoPtioMYhB6ZDO6pA4dm6NXsIEb59CqDPGvyTdnagDa0SVZV6CQKFnewSZBSQ/xITRSZu7IlEShBQmb7oRKe1EoBc/XDzal9UiW0paZNDbhEfvKj+2Wsqj16khflB8qpcEzhaa7LbhE9cXGOKb/ms+0i98POQBpMkPVqnU/kScz0k/ntZnAOfS03P2YpNe0/LaZ3N2D9SpnnBNA==,iv:/I7JxzdvPbcV0hRaiAfPpYFZu/LBBPXAbDQWWvA7aC0=,tag:tsSzyDocVhpwLB9tcw5szA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSFZNNDJxMmV2SWlYM3dz
            RzQ3a0U0NVpFeUtDOE5UVi9wcnJGRGZnTFNjCkt5c2ZDdktCUVdPYklwdlNyVk5H
            UXEydjZCaitaazMzMEdrS1RjUkFlT0kKLS0tIHNvdkZaVUJFS3FMSEpNMkwvRGZC
            RE44enpsTnh0d0JvMTVybzlucHF1RUUKdpfs/Y4mSqTgD0kBXRxadnLrHXBS1a78
            4F10UVqEJlGLGbvgoc7GQdBRHsQAEdhJ4BBiryP88KDvmTkvV7hFbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T03:53:04Z"
    mac: ENC[AES256_GCM,data:oA7grntrU+ketizAHuyKjDo4R3Y/ipmrMSA3e5+eD2PU7LheSwq/VfRi03ajbEaMZeSGkw5zN6O/ZegRsfSi09r/ms7AcWEF+yXOcFX7bNNVIyphUo23sdVoasT10mmGOq8fo0a7CXvUsUlbSKCxgKL9pWGyaVJXndlFEJQ7Bvs=,iv:dYrQoFECGhWrA7nMEqhgRCQrUXdNl87I18XAGFW6uzo=,tag:Nn3wjw5vRSyp/9UVPFO4cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
