apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:jUR6gQbWQ5zzrCWVNcpkru60lTwtqrRfuVntQfIOyyCUubbE,iv:cI0JBp0bNVnEU7b3Z6HtAcmhWNdMZmUkHF4N/OPsiwo=,tag:A0rd5pXT3GkiohOFWFFRfg==,type:str]
    credentials.json: ENC[AES256_GCM,data:TKkw8oQ9+lrP5UgFgQSfMUluxqlzxMkB1Nrz/GLbpZZ4EGCNj0Lwwue+2hU8TRXs64ZZ9XcIo0RRi4bNbg4EpGjOEZ3pNetIwjL7RC3G4NTpDSNsrMpJf5L4gWzv19A1B2TsUC+EeN13VFtbUXDJjGpVSpWkDNL/azxHUxbPiOaBtPQUch4i8H0FiVJ/zbf87cYzj8IwrhrwHE0ZMTtzxRTdyrnPqgeT4TWEiWLEIg==,iv:C9vZqeZJgDTvcXhCueyTuyZlQoQtdScvb9Ya01dOS9A=,tag:8lsKUggl9a2OMhOLIp6kdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa2xHTnF1MFcrM3VBSUhE
            S0JMZngxWS9XZytwVVp3ZHpSL3QwenFDZUFVCjhWcldVWVFhTkh6elNRS1Q3Q01J
            bU5vRjg2NnBGcVhoNTFIVWxDbjdHZ2sKLS0tIGRUeG8wcXFNNmJkTlB4QTVaY1U5
            VUxDUWZSWjlXbFYycS9yYjEwZVdXQ0UKCT4xsiZkpkvtUSHqjBgJMSI/ZH2jb/kk
            4iIluB/cWvANdCuKTQgB3D3OgiTEUCkgbZqqIKiih0/W38mxTEKw+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T04:27:23Z"
    mac: ENC[AES256_GCM,data:W/OHA7P0W0IrIHg7wExUCmWzugZDU+cr16Mk+afDTtBt/7KDnvJpQyAF3ckoqbfeoZ5ab/x39NpQYEQk2QmauhU3PCWw8pSI6b4mWH84HcT111IHlDzQ8rcg6lTnj7JG5L8r9MXXmcZmU7W2lK1djHYvyzhHadtEyY/fstaKlLs=,iv:wqv0uCTcX2Sxyd7RexneNVhzfI6TvrUkOeud+N+69DI=,tag:xM2H0wRW+d4CkyRtco5IWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
