apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:YCDvduKuwsSrDm+8JlojSC1nztd5VBA+WSXWemo6NnA8vqhh,iv:5WgGNMRLcNBjbMnXW0cWqP0izPUTc7fIOxUnsJmkjtg=,tag:ZOapxXkqOuqH0QXRE89lGQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:4Mitbs4uldL0SRHSSoP9eucdqCTl1xd7meoLUH+U8fzIG1Q4LINXBWbJ0t9vYVqbLx6mSQRDBVdJfhjdK4ZLNQ6X1n47i1H2VlZ6vEt18VaMbsgViLHYXnLOm3QR6LFC13G/PqxD3ngBHxJZv8K9fOk+IWgLdsU7osprWrwfK+6nHjUZysz3znmazDVqT/JEAmHnKBDQKkczumcyaZsJqb1sTPdM4hfhMzquwfMJew==,iv:lnZnRGiR7UAu4J51ZF1mRc29LFvQcNrkSTNvqXdWB6o=,tag:MRbWC86KsnFEM1qMNu7Dyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xnwhvndjmhrgn78kzvvnr97v6stdvr4zde7qh7cwl0vj7094pssp0amtv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYnNzOC9JV0p5M1h2TVha
            bVR1U3NqZVNqaDNLclhwMlpxaUhZeGpEU1RrCjRpOEdJRDE4WFBWeTNkUy9CTEov
            ejU1MSsrR1BlaHordFRuWlRtZmNEdFkKLS0tIHVMcDM1dFYzemlCVkIzb1F3NTdn
            VTUzUlFndzliSnZlM0xuaHA5bE9nc1EK/5Us/PnJCi1lr9JRQrEeSjOa1+Py8W3N
            ugELk0wpbdiFNupnP6mT8Ee//KDV1JUY6uQBBrXtyHwRgqEG5aj2FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T21:42:00Z"
    mac: ENC[AES256_GCM,data:mC2DKYRO90BM+MEZyH8HfvAelTIDT44sOy4xvWiIlv+kjL33oC72VBb7Z7hH0ICyHnj0ZeRnlN/2HOH5MhYIFKMIWnB7XHpg2izJGeSiatax5Rm5THn2NS47HZcICT2v1/SrG0RgKxRix96EzgEvPYZmdv5lwhZ9BBJpmShQArA=,iv:RhfF3o051U5LUV8ps0e6NO58a8VRTlD9hJQP6K819Wc=,tag:6RtV9q4BFWeObh70u+d2Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
