---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./configmap.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: librechat-config
    files:
      - ./resources/librechat.yaml
  - name: librechat-initdb
    files:
      - ./resources/librechat.sql
generatorOptions:
  disableNameSuffixHash: true
