---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
      - Discord:
        - icon: discord.png
          href: 'https://discord.com/app'
      - Gmail:
        - icon: gmail.png
          href: 'http://gmail.com'
      - Google Calendar:
        - icon: google-calendar.png
          href: 'https://calendar.google.com'
      - Outlook:
        - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/outlook.png
          href: 'https://outlook.com'
    - Online Media:
      - YouTube:
        - icon: youtube.png
          href: 'https://youtube.com/feed/subscriptions'
      - Spotify:
        - icon: spotify.png
          href: 'http://open.spotify.com'
      - Youtube Music:
        - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/youtube-music.png
          href: 'https://music.youtube.com'
    - Reading:
      - Hacker News:
        - icon: sh-hacker-news
          href: 'https://news.ycombinator.com'
    - Kubernetes:
      - kubesearch:
        - icon: kubernetes-dashboard.png
          href: 'https://kubesearch.dev/'
      - moria-ops:
        - icon: github.png
          href: 'https://github.com/billm/moria-ops'
      - Cluster Template:
        - href: https://github.com/onedr0p/cluster-template
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
      - Cloudflared:
          href: https://dash.cloudflare.com/
          icon: cloudflare-zero-trust.png
          description: Cloudflared Tunnel Status
          widget:
            type: cloudflared
            accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
            tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
            key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
            fields: ["status"]

  settings.yaml: |
    title: Dashboard
    # favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    useEqualHeights: true
    theme: dark
    # background:
    #   image: "https://github.com/billm/moria-ops/blob/main/docs/assets/vincentiu-solomon-ln5drpv_ImI-unsplash.jpg?raw=true"
    #   opacity: 20
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Home:
        style: row
        columns: 5
        icon: mdi-home-analytics
      Media:
        style: column
        icon: mdi-play-circle
      Observability:
        style: column
        icon: mdi-chart-line
      Management:
        style: column
        icon: mdi-cog
      Game Servers:
        style: column
        icon: mdi-space-invaders
      Network:
        style: row
        columns: 5
        icon: mdi-network
      Downloads:
        style: row
        columns: 5
        icon: mdi-download-circle
  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/lds-transparent.png
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Greetings, Citizen."
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
          label: "cluster"
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - openmeteo:
        label: Home
        latitude: ${SECRET_LATITUDE}
        longitude: ${SECRET_LONGITUDE}
        units: imperial
        cache: 5
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
    # - unifi_console:
    #     url: https://192.168.1.1:443
    #     username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
    #     password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
