---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
      - Discord:
        - icon: discord.png
          href: 'https://discord.com/app'
      - Gmail:
        - icon: gmail.png
          href: 'http://gmail.com'
      - Google Calendar:
        - icon: google-calendar.png
          href: 'https://calendar.google.com'
      - Outlook:
        - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/outlook.png
          href: 'https://outlook.com'
    - Online Media:
      - YouTube:
        - icon: youtube.png
          href: 'https://youtube.com/feed/subscriptions'
      - Spotify:
        - icon: spotify.png
          href: 'http://open.spotify.com'
      - Youtube Music:
        - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/youtube-music.png
          href: 'https://music.youtube.com'
    - Reading:
      - Hacker News:
        - icon: sh-hacker-news
          href: 'https://news.ycombinator.com'
    - Kubernetes:
      - kubesearch:
        - icon: kubernetes-dashboard.png
          href: 'https://kubesearch.dev/'
      - moria-ops:
        - icon: github.png
          href: 'https://github.com/billm/moria-ops'
      - Cluster Template:
        - href: https://github.com/onedr0p/cluster-template
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Applications:
      - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel Status
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
              fields: ["status"]
        # - Healthchecks:
        #     href: https://healthchecks.io/
        #     icon: healthchecks.png
        #     description: Healthchecks Internet Uptime
        #     widget:
        #       type: healthchecks
        #       url: https://healthchecks.io/
        #       key: {{HOMEPAGE_VAR_HEALTHCHECK_TOKEN}}
        #       uuid: {{HOMEPAGE_VAR_HEALTHCHECK_UUID}}
        # - Unifi:
        #     href: https://unifi.ui.com
        #     icon: unifi.png
        #     description: Unifi Dashboard
        #     widget:
        #       type: unifi
        #       url: https://unifi.${SECRET_DOMAIN}
        #       username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
        #       password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}

    # - Calendar:
    #     - Agenda:
    #         widget:
    #           type: calendar
    #           view: agenda # optional - possible values monthly, agenda
    #           maxEvents: 15 # optional - defaults to 10
    #           integrations: # optional
    #             - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Sonarr # service name for that widget
    #             - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Radarr # service name for that widget
    #             - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonar>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Readarr # service name for that widget
    # - Infrastructure:
    #     - Portainer:
    #         href: &url https://portainer.${SECRET_DOMAIN}
    #         icon: portainer.png
    #         description: Docker Container Management
    #         widget:
    #           type: portainer
    #           url: http://voyager.internal:9090
    #           env: 1
    #           key: {{HOMEPAGE_VAR_PORTAINER_TOKEN}}
    #     - Unraid:
    #         href: https://nas.${SECRET_DOMAIN}
    #         icon: unraid.png
    #         description: Unraid NAS
    # - Home:
    #     - Home-Assistant:
    #         href: https://hass.${SECRET_DOMAIN}
    #         icon: home-assistant.png
    #         description: Home Automation Software
    #         widget:
    #           type: homeassistant
    #           url: https://hass.${SECRET_DOMAIN}
    #           key: {{HOMEPAGE_VAR_HASS_TOKEN}}
  settings.yaml: |
    title: Dashboard
    # favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    useEqualHeights: true
    theme: dark
    # background:
    #   image: "https://github.com/billm/moria-ops/blob/main/docs/assets/vincentiu-solomon-ln5drpv_ImI-unsplash.jpg?raw=true"
    #   opacity: 20
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Applications:
        style: row
        columns: 4
        Home:
          style: column
          icon: mdi-home-analytics
        Media:
          style: column
          icon: mdi-play-circle
        Network:
          style: column
          icon: mdi-network
        Observability:
          style: column
          icon: mdi-chart-line
      Other Services:
        style: row
        columns: 3
        icon: mdi-server
        header: true
        Management:
          style: column
          icon: mdi-cog
        Game Servers:
          style: column
          icon: mdi-space-invaders
        Downloads:
          style: column
          icon: mdi-download-circle
  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/lds-transparent.png
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Greetings, Citizen."
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
          label: "cluster"
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - openmeteo:
        label: Home
        latitude: ${SECRET_LATITUDE}
        longitude: ${SECRET_LONGITUDE}
        units: imperial
        cache: 5
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
    # - unifi_console:
    #     url: https://192.168.1.1:443
    #     username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
    #     password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
