---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpackerr-secret
  data:
  - secretKey: UN_RADARR_0_API_KEY
    remoteRef:
      key: radarr
      property: api_key
  - secretKey: UN_SONARR_0_API_KEY
    remoteRef:
      key: sonarr
      property: api_key
