---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app readarr
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/moria/apps/default/readarr/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_STORAGECLASS: syno-iscsi-delete
      VOLSYNC_SNAPSHOTCLASS: syno-iscsi-delete
      VOLSYNC_CACHE_SNAPSHOTCLASS: syno-iscsi-delete
