---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama-backend-pvc
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: ollama
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/shared/templates/volsync"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substitute:
      APP: ollama-backend
      VOLSYNC_CLAIM: ollama-backend-data
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_STORAGECLASS: syno-iscsi-delete
      VOLSYNC_SNAPSHOTCLASS: syno-iscsi-delete
      VOLSYNC_CACHE_SNAPSHOTCLASS: syno-iscsi-delete
    substituteFrom:
      - kind: Secret
        name: flux-volsync-secret
  dependsOn:
    - name: volsync
    - name: rook-ceph-cluster
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama-ui-pvc
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: ollama
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/shared/templates/volsync"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substitute:
      APP: ollama-ui
      VOLSYNC_CLAIM: ollama-ui-data
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_STORAGECLASS: syno-iscsi-delete
      VOLSYNC_SNAPSHOTCLASS: syno-iscsi-delete
      VOLSYNC_CACHE_SNAPSHOTCLASS: syno-iscsi-delete
    substituteFrom:
      - kind: Secret
        name: flux-volsync-secret
  dependsOn:
    - name: volsync
    - name: rook-ceph-cluster
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: ollama
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/moria/apps/default/ollama/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substitute:
      BACKEND_CLAIM: ollama-backend-data
      UI_CLAIM: ollama-ui-data
    substituteFrom: []
  dependsOn:
    - name: amd-device-plugin
    - name: ollama-backend-pvc
    - name: ollama-ui-pvc
