---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app lldap
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/lldap/lldap
              # TODO: Switch to release tag on next release
              tag: latest-alpine@sha256:10f5d49defc8dfc0f7464b2c35a86f0b86c818929e02288499b2a1cdb252530d
            env:
              LLDAP_VERBOSE: "true"
              LLDAP_HTTP_URL: "https://ldap.${SECRET_DOMAIN}"
              LLDAP_HTTP_PORT: &port 80
              LLDAP_LDAP_PORT: &ldapPort 389
              LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "true"
              LLDAP_SMTP_OPTIONS__SERVER: "mail-relay.networking.svc.cluster.local"
              LLDAP_SMTP_OPTIONS__PORT: "25"
              LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "NONE"
              LLDAP_SMTP_OPTIONS__FROM: "Infrastructure <infrastructure@${SECRET_DOMAIN}>"
              LLDAP_SMTP_OPTIONS__REPLY_TO: "Do not reply <noreply@${SECRET_DOMAIN}>"
            envFrom:
              - secretRef:
                  name: lldap-secrets
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      main:
        ports:
          http:
            port: *port
          ldap:
            enabled: true
            port: *ldapPort

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          hajimari.io/icon: icon-park-twotone:data-user
        hosts:
          - host: &host "ldap.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: data-lldap

