---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: windmill
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: windmill-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        WINDMILL_POSTGRES_URL: "postgres://{{ .DB_USER }}:{{ .DB_PASS }}@postgres-rw.database.svc.cluster.local/{{ .DB_NAME }}?sslmode=disable"
        # Postgres Init
        POSTGRES_DBNAME: {{ .DB_NAME }}
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: {{ .DB_USER }}
        POSTGRES_PASS: "{{ .DB_PASS }}"
        POSTGRES_INIT_FILE: /etc/init.sql

  dataFrom:
    - extract:
        key: windmill
    - extract:
        key: cloudnative-pg
